# Example configuration for Julia NetCDF to CSV pipeline
# Copy this file and modify paths for your specific setup

# Variable configuration
variable: "qr" # Options: qtot, dis, qr
temporal_resolution: "monthly"
spatial_method: "sum" # sum or mean

# Climate model configuration
isimip_version: "3b"
climate_model: "gfdl-esm4"
scenario: "ssp126" # ssp126, ssp370, ssp585
data_period: "future" # historical or future

# Regional configuration
region: "R12" # R11, R12, or country code

# File paths (OS-neutral - use forward slashes, Julia will handle conversion)
# Relative paths are resolved from the Julia script location

# Paths (configurable)
input_dir: "/mnt/p/watxene/ISIMIP/ISIMIP3b/OutputData"
basin_shapefile: "/home/raghunathan/ISIMIP/basins_delineated/basins_by_region_R12.shp"
output_dir: "./hydro_output"

# input_dir: "${HOME}/data/isimip/netcdf"
# basin_shapefile: "${MESSAGE_DATA_PATH}/water/delineation/basins_by_region_simpl_R12.shp"
# output_dir: "${HOME}/output/water/csv"

# Processing parameters
chunk_size: 1000
parallel_processing: true

# Multiple scenarios can be processed in batch
scenarios:
  - name: "ssp126_low"
    scenario: "ssp126"
    climate_model: "gfdl-esm4"
  - name: "ssp370_medium"
    scenario: "ssp370"
    climate_model: "gfdl-esm4"
  - name: "ssp585_high"
    scenario: "ssp585"
    climate_model: "gfdl-esm4"

# Variables to process in batch
variables:
  - "qtot"
  - "dis"
  - "qr"
